version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.kongrentian.com
    container_name: gitlab 
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.kongrentian.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - 80:80
      - 443:443
      - 2224:22
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
