server_user: jingyangzhenren
default_account: "{{ server_user }}"
ansible_user: "{{ server_user }}"
server_home: /home/{{ server_user }}
dotfiles_repo: https://github.com/jingyangzhenren/config-personal-dotfiles.git
dotfiles_dir: "{{ server_home }}/Dotfiles"
github_account: "{{ default_account }}"
github_repositories:
  - app-web-anki-plugin
email: 97828377+jingyangzhenren@users.noreply.github.com
