#cloud-config

groups:
  - docker

users:
  - default
  - name: "${ci_user}"
    gecos: ci user
    shell: /bin/bash
    ssh_authorized_keys:
      - "${main_key}"
      - "${ci_key}"

  - name: "${server_user}"
    gecos: personal user
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - "${main_key}"

ssh_pwauth: false

# Upgrade the instance on first boot
package_upgrade: true
