#!/bin/sh
#
# By default, dmenu_path sorts executables alphabetically. It seems to make
# more sense to sort them by atime in an effort to reduce the number of
# keystrokes needed to start a program.

echo $PATH | tr ':' '\n' | uniq | sed 's#$#/#' | # lists directories in $PATH
    xargs ls -lu --time-style=+%s |              # adds atime epoch
    awk '/^(-|l)/ { print $6, $7 }' |            # remove everything but timestamp and name
    sort -rn | cut -d' ' -f 2                    # Sort based on the timestamp and then remove it