- ansible.builtin.import_playbook: setup_server.yml

- name: >-
    {{ playbook_name }} | Setup GitHub Actions Runner
  hosts: "{{ host | default('ci') }}"
  become: true
  tags:
    - deploy
    - github_runner
  vars:
    playbook_name: github_runner.yml
    access_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    runner_labels:
      - ci
    reinstall_runner: yes
    runner_user: "{{ server_user }}"
    runner_name: "{{ inventory_hostname }}-{{ ansible_hostname }}"
  tasks:
    - name: >-
        {{ playbook_name }} | Setup github runner for every repository
      include_role:
        role: monolithprojects.github_actions_runner
      loop: "{{ github_repositories }}"
      loop_control:
        loop_var: github_repo
