- name: >-
    {{ playbook_name }} | Setup ssh config
  hosts: "{{ host | default('all') }}"
  tags:
    - setup
    - dotfiles
  vars:
    playbook_name: setup_dotfiles.yml
  tasks:
    - name: >-
        {{ playbook_name }} | Check current user
      ansible.builtin.assert:
        that: ansible_user != "root"

    - name: >-
        {{ playbook_name }} | Clone dotfiles
      ansible.builtin.git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        force: true

    - name: >-
        {{ playbook_name }} | Link bashrc from dotfiles
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/scripts/bashrc.sh"
        dest: "{{ server_home }}/.bashrc"
        state: link
        force: true
