- name: >-
    {{ playbook_name }} | Setup ssh config
  hosts: "{{ host | default('all') }}"
  tags:
    - setup
    - ssh
  vars:
    playbook_name: setup_ssh_config.yml
  tasks:
    - name: >-
        {{ playbook_name }} | Setup ssh config using the inventory
      ansible.builtin.template:
        src: ssh_config.txt
        dest: "{{ server_home }}/.ssh/config"
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: 0600
