- name: >-
    {{ playbook_name }} | Initial server setup
  hosts: "{{ host | default('all') }}"
  become: true
  gather_facts: true
  tags:
    - setup
    - server
  vars:
    ansible_user: "{{ initial_user | default(server_user) }}"
    playbook_name: setup_server.yml

  pre_tasks:
    - name: >-
        {{ playbook_name }} | Lock root password
      ansible.builtin.user:
        name: root
        password: !

    - name: >-
        {{ playbook_name }} | Create {{ server_user }} user with locked password
      ansible.builtin.user:
        name: "{{ server_user }}"
        shell: /bin/bash
        groups: docker
        append: yes
        generate_ssh_key: yes
        password: !

    - name: >-
        {{ playbook_name }} | Add SSH key
      ansible.posix.authorized_key:
        user: "{{ server_user }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

    - name: >-
        {{ playbook_name }} | Allow {{ server_user }} to run all commands
        without a password
      community.general.sudoers:
        name: allow {{ server_user }} to run all commands without a password
        state: present
        user: "{{ server_user }}"
        commands: ALL

- ansible.builtin.import_playbook: setup_harden_os.yml

- ansible.builtin.import_playbook: setup_ssh.yml

- ansible.builtin.import_playbook: setup_dotfiles.yml
