- name: ensure that an old docker is not installed
  ansible.builtin.yum:
      name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
      state: absent

- name: ensure that the yum packages are installed
  ansible.builtin.yum:
      name:
          - "*"
          - python3
          - python3-pip
          - policycoreutils-python
          - openssl
          - curl
          - openssh-server
          - perl
      state: latest

- name: ensure that the pip packages are installed
  ansible.builtin.pip:
      name:
          - pip
          - docker
      state: latest

- name: install docker and docker compose
  ansible.builtin.shell: >-
      curl -fsSL https://get.docker.com | sh;
      curl -fsSL
        "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
        -o /usr/local/bin/docker-compose;
      chmod +x /usr/local/bin/docker-compose

- name: create the user
  ansible.builtin.user:
      name: "{{ main_user }}"
      groups: docker
      append: yes
      password: >-
          {{
            lookup(
              'password',
              inventory_hostname
              + '_' + main_user
              + '_password.txt'
            )
          }}
      update_password: on_create

- name: enable sudo without password
  ansible.builtin.lineinfile:
      path: /etc/sudoers
      line: kongrentian ALL=(ALL) NOPASSWD:ALL

- name: copy dot files
  ansible.builtin.copy:
      src: /home/borinskikh/dot-files/
      dest: dot-files
      mode: 0770
      owner: kongrentian
