- name: start docker-compose
  environment:
      GITLAB_HOME: /srv/gitlab
      GITLAB_ROOT_PASSWORD: "{{ lookup('password', gitlab_password_file) }}"
  community.docker.docker_compose:
      definition: "{{ lookup('template', 'gitlab.yml') }}"
      state: present
      pull: yes

- name: fetch password file
  ansible.builtin.fetch:
      src: "{{ gitlab_password_file }}"
      dest: "{{ lookup('env', 'HOME') }}/credentials"

- name: delete password file
  ansible.builtin.file:
      path: "{{ gitlab_password_file }}"
      state: absent
